/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QrIndexRouteImport } from './routes/qr/index'
import { Route as PdfIndexRouteImport } from './routes/pdf/index'
import { Route as QrGeneratorRouteImport } from './routes/qr/generator'
import { Route as PdfSplitRouteImport } from './routes/pdf/split'
import { Route as PdfMergeRouteImport } from './routes/pdf/merge'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrIndexRoute = QrIndexRouteImport.update({
  id: '/qr/',
  path: '/qr/',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfIndexRoute = PdfIndexRouteImport.update({
  id: '/pdf/',
  path: '/pdf/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrGeneratorRoute = QrGeneratorRouteImport.update({
  id: '/qr/generator',
  path: '/qr/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfSplitRoute = PdfSplitRouteImport.update({
  id: '/pdf/split',
  path: '/pdf/split',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfMergeRoute = PdfMergeRouteImport.update({
  id: '/pdf/merge',
  path: '/pdf/merge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/pdf/merge': typeof PdfMergeRoute
  '/pdf/split': typeof PdfSplitRoute
  '/qr/generator': typeof QrGeneratorRoute
  '/pdf/': typeof PdfIndexRoute
  '/qr/': typeof QrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/pdf/merge': typeof PdfMergeRoute
  '/pdf/split': typeof PdfSplitRoute
  '/qr/generator': typeof QrGeneratorRoute
  '/pdf': typeof PdfIndexRoute
  '/qr': typeof QrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/pdf/merge': typeof PdfMergeRoute
  '/pdf/split': typeof PdfSplitRoute
  '/qr/generator': typeof QrGeneratorRoute
  '/pdf/': typeof PdfIndexRoute
  '/qr/': typeof QrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/pdf/merge'
    | '/pdf/split'
    | '/qr/generator'
    | '/pdf/'
    | '/qr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/pdf/merge'
    | '/pdf/split'
    | '/qr/generator'
    | '/pdf'
    | '/qr'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/pdf/merge'
    | '/pdf/split'
    | '/qr/generator'
    | '/pdf/'
    | '/qr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  PdfMergeRoute: typeof PdfMergeRoute
  PdfSplitRoute: typeof PdfSplitRoute
  QrGeneratorRoute: typeof QrGeneratorRoute
  PdfIndexRoute: typeof PdfIndexRoute
  QrIndexRoute: typeof QrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/': {
      id: '/qr/'
      path: '/qr'
      fullPath: '/qr/'
      preLoaderRoute: typeof QrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf/': {
      id: '/pdf/'
      path: '/pdf'
      fullPath: '/pdf/'
      preLoaderRoute: typeof PdfIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/generator': {
      id: '/qr/generator'
      path: '/qr/generator'
      fullPath: '/qr/generator'
      preLoaderRoute: typeof QrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf/split': {
      id: '/pdf/split'
      path: '/pdf/split'
      fullPath: '/pdf/split'
      preLoaderRoute: typeof PdfSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf/merge': {
      id: '/pdf/merge'
      path: '/pdf/merge'
      fullPath: '/pdf/merge'
      preLoaderRoute: typeof PdfMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  PdfMergeRoute: PdfMergeRoute,
  PdfSplitRoute: PdfSplitRoute,
  QrGeneratorRoute: QrGeneratorRoute,
  PdfIndexRoute: PdfIndexRoute,
  QrIndexRoute: QrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
