/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplitRouteImport } from './routes/split'
import { Route as QrGeneratorRouteImport } from './routes/qr-generator'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as IndexRouteImport } from './routes/index'

const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const QrGeneratorRoute = QrGeneratorRouteImport.update({
  id: '/qr-generator',
  path: '/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merge': typeof MergeRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/split': typeof SplitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merge': typeof MergeRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/split': typeof SplitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/merge': typeof MergeRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/split': typeof SplitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/merge' | '/qr-generator' | '/split'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/merge' | '/qr-generator' | '/split'
  id: '__root__' | '/' | '/merge' | '/qr-generator' | '/split'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MergeRoute: typeof MergeRoute
  QrGeneratorRoute: typeof QrGeneratorRoute
  SplitRoute: typeof SplitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-generator': {
      id: '/qr-generator'
      path: '/qr-generator'
      fullPath: '/qr-generator'
      preLoaderRoute: typeof QrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MergeRoute: MergeRoute,
  QrGeneratorRoute: QrGeneratorRoute,
  SplitRoute: SplitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
